const PropertyDetail = [
  {
    id: "1",
    Image: "PropertyImages/london park.jpg",
    heading: "London Park & Gardens",
    span: "Ologuneru,Ibadan.",
    amount: "3,500,000",
    size: "540 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "2",
    Image: "PropertyImages/cpgasj.jpeg",
    heading: "City Park & Gardens",
    span: "Asejire,Ibadan.",
    amount: "5,000,000",
    size: "540 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "3",
    Image: "PropertyImages/TreasurePark.jpeg",
    heading: "Treasure Park and Gardens, phase 3",
    span: "Shimawa,Ogun",
    amount: "13,000,000",
    size: "600 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "4",
    Image: "PropertyImages/West park.jpeg",
    heading: "West park & Gardens",
    span: "Aiyegun-Oleyo, Ibadan.",
    amount: "4,500,000",
    size: "270 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "5",
    Image: "PropertyImages/Winter park and gardens.jpeg",
    heading: "Winter park and gardens",
    span: "Sagamu,Ogun State",
    amount: "10,000,000",
    size: "54s0 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "6",
    Image: "PropertyImages/town park and Gardens imota ogun.jpeg",
    heading: "Town Park & Gardens",
    span: "Imota,Ogun State",
    amount: "4,000,000",
    size: "600 Sqm",
    type: "Land",
    currency: "₦",
  },
];

export default PropertyDetail;
