const PropertyDetail = [
  {
    id: "1",
    Image: "PropertyImages/London park and gardens.jpeg",
    heading: "London Park & Gardens",
    span: "Ologuneru,Ibadan.",
    amount: "3,000,000",
    size: "540 Sqmt",
    type: "Land",
    currency: "₦",
  },
  {
    id: "2",
    Image: "PropertyImages/cty park and garden.png",
    heading: "City Park & Gardens",
    span: "Asejire,Ibadan.",
    amount: "3,000,000",
    size: "540 Sqmt",
    type: "Land",
    currency: "₦",
  },
  {
    id: "3",
    Image: "PropertyImages/west park.jpg",
    heading: "West Park & Gardens",
    span: "Aiyegun-Oleyo,Ibadan",
    amount: "6,000,000",
    size: "540 Sqmt",
    type: "Land",
    currency: "₦",
  },
  {
    id: "4",
    Image: "PropertyImages/rosewood.jpeg",
    heading: "Rosewood Park & Gardens",
    span: "Bako-Apata, Ibadan.",
    amount: "3,000,000",
    size: "540 Sqmt",
    type: "Land",
    currency: "₦",
  },
  {
    id: "5",
    Image: "PropertyImages/WhatsApp-Image-2021-03-17-at-16.45.56.jpeg",
    heading: "Imperial Park & Gardens",
    span: "Sagamu,Ogun State",
    amount: "4,500,000",
    size: "600 Sqmt",
    type: "Land",
    currency: "₦",
  },
];

export default PropertyDetail;
