const PropertyDetail = [
  {
    id: "1",
    Image: "PropertyImages/london park.jpg",
    heading: "London Park & Gardens",
    span: "Ologuneru,Ibadan.",
    amount: "3,500,000",
    size: "540 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "2",
    Image: "PropertyImages/town park and Gardens imota ogun.jpeg",
    heading: "Town Park & Gardens",
    span: "Imota,Ogun State",
    amount: "4,000,000",
    size: "600 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "3",
    Image: "PropertyImages/TreasurePark.jpeg",
    heading: "Treasure Park and Gardens, phase 3",
    span: "Shimawa,Ogun",
    amount: "13,000,000",
    size: "600 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "4",
    Image: "PropertyImages/West park.jpeg",
    heading: "West park & Gardens",
    span: "Aiyegun-Oleyo, Ibadan.",
    amount: "9,000,000",
    size: "270 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "5",
    Image: "PropertyImages/Winter park and gardens.jpeg",
    heading: "Winter park and gardens",
    span: "Sagamu,Ogun State",
    amount: "10,000,000",
    size: "540 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "6",
    Image: "PropertyImages/cpgasj.jpeg",
    heading: "City Park & Gardens",
    span: "Asejire,Ibadan.",
    amount: "5,000,000",
    size: "540 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "7",
    Image: "PropertyImages/ekocity.jpeg",
    heading: "Eko City, Ile-Aje",
    span: "Lekki-Epe",
    amount: "100,000,000",
    size: "500 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "8",
    Image: "PropertyImages/grandview.jpeg",
    heading: "Grandview Park & Gardens",
    span: "Atan-Ota,Ogun State",
    amount: "5,000,000",
    size: "648 Sqm",
    type: "Land",
    currency: "₦",
  },
  {
    id: "9",
    Image: "PropertyImages/rome.jpeg",
    heading: "City of Rome.",
    span: "Imota Emuren,Ogun State",
    amount: "7,000,000",
    size: "600 Sqm",
    type: "Land",
    currency: "₦",
  },
];

export default PropertyDetail;
